import type { InstrumentCatalogueEntry, GeographyCode } from '../types/instrumentCatalogue'
import { TRACK_ONLY_TYPES } from '../types/instrumentCatalogue'

// ─────────────────────────────────────────────────────────────
// Kāshe Instrument Catalogue — V1 static seed
// Supabase table in V2 — identical schema.
// role:'suggest'    → InstrumentDiscoverySection
// role:'track_only' → Portfolio tracker only, never suggested
// Never affiliate links. Never buy/sell language.
// ─────────────────────────────────────────────────────────────

export const INSTRUMENT_CATALOGUE: InstrumentCatalogueEntry[] = [

  // ── GROWTH TIER 0 — Broad Market EU/BeNeLux/DE ─────────────

  {
    id: 'vwce',
    name: 'VWCE — Vanguard FTSE All-World (Accumulating)',
    ticker: 'VWCE',
    isin: 'IE00BK5BQT80',
    type: 'etf',
    bucket: 'GROWTH',
    tier: 0,
    role: 'suggest',
    residenceGeographies: ['NL','BE','DE','LU','IE','GLOBAL_EU'],
    domicile: 'IE',
    regulatoryRegime: 'UCITS',
    eligibleWrappers: ['taxable'],
    currency: 'EUR',
    platforms: [
      { name: 'DeGiro', geographies: ['NL','BE','DE'] },
      { name: 'IBKR', geographies: ['NL','BE','DE','LU'] },
      { name: 'Scalable Capital', geographies: ['DE','NL'] },
      { name: 'Trade Republic', geographies: ['DE','NL','BE'] },
    ],
    description: 'The entire world — ~3,700 companies — in one accumulating ETF.',
    why: 'The default starting point for EU-based investors. Dividends reinvest automatically — no manual action, maximum compounding.',
    expenseRatio: '0.22%',
    terFootnote: true,
    riskTier: 'medium',
    liquidityHorizon: 't_plus_1',
    tags: ['passive','broad-market','accumulating','low-cost','ucits','eur-traded'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  {
    id: 'vwrl',
    name: 'VWRL — Vanguard FTSE All-World (Distributing)',
    ticker: 'VWRL',
    isin: 'IE00B3RBWM25',
    type: 'etf',
    bucket: 'GROWTH',
    tier: 0,
    role: 'suggest',
    residenceGeographies: ['NL','BE','DE','LU','IE','GLOBAL_EU'],
    domicile: 'IE',
    regulatoryRegime: 'UCITS',
    eligibleWrappers: ['taxable'],
    currency: 'USD',
    platforms: [
      { name: 'DeGiro', geographies: ['NL','BE','DE'], notes: 'Free on core selection list' },
      { name: 'IBKR', geographies: ['NL','BE','DE','LU'] },
      { name: 'Bolero', geographies: ['BE'] },
    ],
    description: 'Same global equity exposure as VWCE — pays dividends quarterly rather than reinvesting.',
    why: 'Worth exploring if you prefer dividend income over automatic reinvestment.',
    expenseRatio: '0.22%',
    terFootnote: true,
    riskTier: 'medium',
    liquidityHorizon: 't_plus_1',
    tags: ['passive','broad-market','distributing','low-cost','ucits'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  {
    id: 'iwda',
    name: 'IWDA — iShares Core MSCI World ETF',
    ticker: 'IWDA',
    isin: 'IE00B4L5Y983',
    type: 'etf',
    bucket: 'GROWTH',
    tier: 0,
    role: 'suggest',
    residenceGeographies: ['NL','BE','DE','LU','IE','GLOBAL_EU'],
    domicile: 'IE',
    regulatoryRegime: 'UCITS',
    eligibleWrappers: ['taxable'],
    currency: 'USD',
    platforms: [
      { name: 'DeGiro', geographies: ['NL','BE','DE'], notes: 'Free on core selection list' },
      { name: 'IBKR', geographies: ['NL','BE','DE','LU'] },
      { name: 'Scalable Capital', geographies: ['DE','NL'] },
      { name: 'Trade Republic', geographies: ['DE','NL','BE'] },
    ],
    description: 'Developed markets only — 23 countries, ~1,400 companies. Excludes emerging markets.',
    why: 'Pairs with EMIM for investors who want to control emerging market allocation separately from developed markets.',
    expenseRatio: '0.20%',
    terFootnote: true,
    riskTier: 'medium',
    liquidityHorizon: 't_plus_1',
    tags: ['passive','developed-markets','low-cost','ucits'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  {
    id: 'eunl',
    name: 'EUNL — iShares Core MSCI World (XETRA)',
    ticker: 'EUNL',
    isin: 'IE00B4L5Y983',
    type: 'etf',
    bucket: 'GROWTH',
    tier: 0,
    role: 'suggest',
    residenceGeographies: ['DE'],
    domicile: 'IE',
    regulatoryRegime: 'UCITS',
    eligibleWrappers: ['taxable'],
    currency: 'EUR',
    platforms: [
      { name: 'Scalable Capital', geographies: ['DE'], notes: 'Free in Prime+ plan' },
      { name: 'Trade Republic', geographies: ['DE'], notes: 'Sparplan eligible' },
      { name: 'Comdirect', geographies: ['DE'] },
      { name: 'DKB', geographies: ['DE'] },
      { name: 'Flatex', geographies: ['DE'] },
    ],
    description: 'MSCI World listed on XETRA in EUR. Germany\'s default ETF Sparplan choice.',
    why: 'The natural starting point for German investors. EUR-denominated, Sparplan-eligible across all major German brokers.',
    expenseRatio: '0.20%',
    terFootnote: true,
    riskTier: 'medium',
    liquidityHorizon: 't_plus_1',
    tags: ['passive','broad-market','xetra','sparplan','ucits','eur-traded','germany'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  // ── GROWTH TIER 1 — Regional Tilt EU ───────────────────────

  {
    id: 'cspx',
    name: 'CSPX — iShares Core S&P 500 ETF',
    ticker: 'CSPX',
    isin: 'IE00B5BMR087',
    type: 'etf',
    bucket: 'GROWTH',
    tier: 1,
    role: 'suggest',
    residenceGeographies: ['NL','BE','DE','LU','IE','GLOBAL_EU'],
    domicile: 'IE',
    regulatoryRegime: 'UCITS',
    eligibleWrappers: ['taxable'],
    currency: 'USD',
    platforms: [
      { name: 'DeGiro', geographies: ['NL','BE','DE'] },
      { name: 'IBKR', geographies: ['NL','BE','DE','LU'] },
      { name: 'Scalable Capital', geographies: ['DE','NL'] },
    ],
    description: '500 largest US companies. Adds a deliberate US large-cap tilt.',
    why: 'A common complement once you hold a world ETF — for investors who want more US weight than VWCE provides.',
    expenseRatio: '0.07%',
    terFootnote: true,
    riskTier: 'medium',
    liquidityHorizon: 't_plus_1',
    tags: ['passive','us-equity','large-cap','low-cost','ucits'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  {
    id: 'emim',
    name: 'EMIM — iShares Core MSCI EM IMI ETF',
    ticker: 'EMIM',
    isin: 'IE00BKM4GZ66',
    type: 'etf',
    bucket: 'GROWTH',
    tier: 1,
    role: 'suggest',
    residenceGeographies: ['NL','BE','DE','LU','IE','GLOBAL_EU'],
    domicile: 'IE',
    regulatoryRegime: 'UCITS',
    eligibleWrappers: ['taxable'],
    currency: 'USD',
    platforms: [
      { name: 'DeGiro', geographies: ['NL','BE','DE'], notes: 'Free on core selection list' },
      { name: 'IBKR', geographies: ['NL','BE','DE','LU'] },
    ],
    description: 'Emerging markets — India, China, Brazil, Taiwan and more.',
    why: 'Pairs with IWDA to build a complete world portfolio with explicit EM control.',
    expenseRatio: '0.18%',
    terFootnote: true,
    riskTier: 'medium_high',
    liquidityHorizon: 't_plus_1',
    tags: ['passive','emerging-markets','india-exposure','low-cost','ucits'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  {
    id: 'xnas',
    name: 'XNAS — Xtrackers Nasdaq 100 ETF',
    ticker: 'XNAS',
    isin: 'LU0274209237',
    type: 'etf',
    bucket: 'GROWTH',
    tier: 1,
    role: 'suggest',
    residenceGeographies: ['NL','BE','DE','LU','IE','GLOBAL_EU'],
    domicile: 'LU',
    regulatoryRegime: 'UCITS',
    eligibleWrappers: ['taxable'],
    currency: 'EUR',
    platforms: [
      { name: 'DeGiro', geographies: ['NL','BE','DE'] },
      { name: 'Scalable Capital', geographies: ['DE','NL'] },
      { name: 'Trade Republic', geographies: ['DE','NL','BE'] },
    ],
    description: '100 largest non-financial Nasdaq companies. Concentrated US tech exposure.',
    why: 'For investors who want explicit technology sector weight beyond what a world ETF provides. Higher volatility than CSPX.',
    expenseRatio: '0.20%',
    terFootnote: true,
    riskTier: 'high',
    liquidityHorizon: 't_plus_1',
    tags: ['passive','tech','nasdaq','higher-volatility','ucits'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  // ── GROWTH TIER 2 — Factor / Thematic EU ───────────────────

  {
    id: 'iwfq',
    name: 'IWFQ — iShares MSCI World Quality Factor ETF',
    ticker: 'IWFQ',
    isin: 'IE00BD1F4L37',
    type: 'etf',
    bucket: 'GROWTH',
    tier: 2,
    role: 'suggest',
    residenceGeographies: ['NL','BE','DE','LU','IE','GLOBAL_EU'],
    domicile: 'IE',
    regulatoryRegime: 'UCITS',
    eligibleWrappers: ['taxable'],
    currency: 'USD',
    platforms: [
      { name: 'DeGiro', geographies: ['NL','BE','DE'] },
      { name: 'IBKR', geographies: ['NL','BE','DE','LU'] },
    ],
    description: 'Global companies with high return on equity, stable earnings, low leverage.',
    why: 'Quality factor has historically outperformed broad market over long periods with lower drawdowns.',
    expenseRatio: '0.30%',
    terFootnote: true,
    riskTier: 'medium',
    liquidityHorizon: 't_plus_1',
    tags: ['factor','quality','satellite','ucits'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  {
    id: 'wsml',
    name: 'WSML — iShares MSCI World Small Cap ETF',
    ticker: 'WSML',
    isin: 'IE00BF4RFH31',
    type: 'etf',
    bucket: 'GROWTH',
    tier: 2,
    role: 'suggest',
    residenceGeographies: ['NL','BE','DE','LU','IE','GLOBAL_EU'],
    domicile: 'IE',
    regulatoryRegime: 'UCITS',
    eligibleWrappers: ['taxable'],
    currency: 'USD',
    platforms: [
      { name: 'DeGiro', geographies: ['NL','BE','DE'] },
      { name: 'IBKR', geographies: ['NL','BE','DE','LU'] },
    ],
    description: 'Small-cap companies across developed markets. Higher long-run potential, higher volatility.',
    why: 'Small-cap premium is one of the most documented factor returns. Needs a long horizon to realise.',
    expenseRatio: '0.35%',
    terFootnote: true,
    riskTier: 'high',
    liquidityHorizon: 't_plus_1',
    tags: ['factor','small-cap','satellite','ucits','long-horizon'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  // ── GROWTH TIER 3 — Direct Equity EU ───────────────────────

  {
    id: 'degiro-direct-equity',
    name: 'Individual stocks on DeGiro',
    type: 'direct_equity',
    bucket: 'GROWTH',
    tier: 3,
    role: 'suggest',
    residenceGeographies: ['NL','BE','DE','LU','IE','GLOBAL_EU'],
    domicile: 'GLOBAL_EU',
    regulatoryRegime: 'exchange_listed',
    eligibleWrappers: ['taxable'],
    currency: 'EUR',
    platforms: [
      { name: 'DeGiro', geographies: ['NL','BE','DE'], notes: 'Access to 50+ exchanges globally' },
    ],
    description: 'Individual company shares on any major global exchange via DeGiro.',
    why: 'For the 5–10% of your portfolio you want to manage actively. Not a replacement for a diversified core.',
    terFootnote: false,
    riskTier: 'very_high',
    liquidityHorizon: 't_plus_2',
    riskWarning: 'Individual stocks carry company-specific risk. A single stock can go to zero.',
    tags: ['direct-equity','active','high-risk','degiro'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  {
    id: 'ibkr-direct-equity',
    name: 'Individual stocks on IBKR',
    type: 'direct_equity',
    bucket: 'GROWTH',
    tier: 3,
    role: 'suggest',
    residenceGeographies: ['NL','BE','DE','LU','IE','GB','US','GLOBAL'],
    domicile: 'GLOBAL',
    regulatoryRegime: 'exchange_listed',
    eligibleWrappers: ['taxable','ISA','SIPP'],
    currency: 'USD',
    platforms: [
      { name: 'IBKR', geographies: ['NL','BE','DE','LU','GB','US'], notes: 'Access to 150+ markets globally' },
      { name: 'IBKR_US', geographies: ['US'] },
    ],
    description: 'Individual stocks on 150+ markets globally via Interactive Brokers.',
    why: 'Best option for globally mobile investors who need multi-currency stock access across geographies.',
    terFootnote: false,
    riskTier: 'very_high',
    liquidityHorizon: 't_plus_2',
    riskWarning: 'Individual stocks carry company-specific risk. A single stock can go to zero.',
    tags: ['direct-equity','active','global','multi-currency','ibkr'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  // ── GROWTH — India ──────────────────────────────────────────

  {
    id: 'nifty50-index',
    name: 'Nifty 50 Index Fund (Direct)',
    type: 'index_fund',
    bucket: 'GROWTH',
    tier: 0,
    role: 'suggest',
    residenceGeographies: ['IN'],
    domicile: 'IN',
    regulatoryRegime: 'SEBI',
    eligibleWrappers: ['NRE','NRO','taxable'],
    currency: 'INR',
    platforms: [
      { name: 'Zerodha_Coin', geographies: ['IN'] },
      { name: 'Groww', geographies: ['IN'] },
      { name: 'Kuvera', geographies: ['IN'], notes: 'Direct plans only — lowest TER' },
      { name: 'MFCentral', geographies: ['IN'] },
      { name: 'INDmoney', geographies: ['IN'], notes: 'NRI-friendly KYC' },
    ],
    description: 'India\'s 50 largest listed companies — the benchmark for Indian equity.',
    why: 'The default starting point for India equity. Always choose direct plan to minimise TER drag.',
    expenseRatio: '0.10–0.20%',
    terFootnote: true,
    riskTier: 'medium',
    liquidityHorizon: 't_plus_1',
    tags: ['passive','india','large-cap','direct-plan','sebi','nri-eligible'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  {
    id: 'nifty-next50',
    name: 'Nifty Next 50 Index Fund (Direct)',
    type: 'index_fund',
    bucket: 'GROWTH',
    tier: 1,
    role: 'suggest',
    residenceGeographies: ['IN'],
    domicile: 'IN',
    regulatoryRegime: 'SEBI',
    eligibleWrappers: ['NRE','NRO','taxable'],
    currency: 'INR',
    platforms: [
      { name: 'Zerodha_Coin', geographies: ['IN'] },
      { name: 'Groww', geographies: ['IN'] },
      { name: 'Kuvera', geographies: ['IN'] },
    ],
    description: 'Ranks 51–100 by market cap — tomorrow\'s Nifty 50.',
    why: 'Natural complement to Nifty 50. Many Indian investors hold both for broad large-to-mid cap coverage.',
    expenseRatio: '0.15–0.30%',
    terFootnote: true,
    riskTier: 'medium_high',
    liquidityHorizon: 't_plus_1',
    tags: ['passive','india','mid-large-cap','direct-plan','sebi'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  {
    id: 'ppfas-flexicap',
    name: 'PPFAS Flexi Cap Fund (Direct)',
    type: 'active_mutual_fund',
    bucket: 'GROWTH',
    tier: 2,
    role: 'suggest',
    residenceGeographies: ['IN'],
    domicile: 'IN',
    regulatoryRegime: 'SEBI',
    eligibleWrappers: ['NRE','NRO','taxable'],
    currency: 'INR',
    platforms: [
      { name: 'Kuvera', geographies: ['IN'] },
      { name: 'MFCentral', geographies: ['IN'] },
    ],
    description: 'Active flexi-cap fund with partial international equity allocation.',
    why: 'Widely regarded for low costs, aligned management, and long-term philosophy. No distributor commissions.',
    expenseRatio: '~0.59%',
    terFootnote: true,
    riskTier: 'medium_high',
    liquidityHorizon: 't_plus_1',
    tags: ['active','flexi-cap','india','international-exposure','direct-plan'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  {
    id: 'zerodha-direct-equity-in',
    name: 'Individual stocks on Zerodha',
    type: 'direct_equity',
    bucket: 'GROWTH',
    tier: 3,
    role: 'suggest',
    residenceGeographies: ['IN'],
    domicile: 'IN',
    regulatoryRegime: 'SEBI',
    eligibleWrappers: ['NRO','PIS','taxable'],
    currency: 'INR',
    platforms: [
      { name: 'Zerodha', geographies: ['IN'], notes: 'NRIs via Zerodha NRI account (PIS route)' },
    ],
    description: 'NSE and BSE listed stocks via Zerodha — India\'s largest retail broker.',
    why: 'For investors who want direct India equity exposure beyond index funds. NRIs require PIS account setup.',
    terFootnote: false,
    riskTier: 'very_high',
    liquidityHorizon: 't_plus_1',
    riskWarning: 'Individual stocks carry company-specific risk. NRI investment in Indian equities has regulatory limits.',
    tags: ['direct-equity','india','active','nri-eligible-via-pis','sebi'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  // ── GROWTH — United States ──────────────────────────────────

  {
    id: 'vti',
    name: 'VTI — Vanguard Total Stock Market ETF',
    ticker: 'VTI',
    isin: 'US9229087690',
    type: 'etf',
    bucket: 'GROWTH',
    tier: 0,
    role: 'suggest',
    residenceGeographies: ['US'],
    domicile: 'US',
    regulatoryRegime: 'SEC',
    eligibleWrappers: ['Roth_IRA','Traditional_IRA','401k_traditional','401k_roth','taxable_brokerage_US'],
    currency: 'USD',
    platforms: [
      { name: 'Fidelity', geographies: ['US'] },
      { name: 'Vanguard_US', geographies: ['US'] },
      { name: 'Schwab', geographies: ['US'] },
      { name: 'IBKR_US', geographies: ['US'] },
    ],
    description: 'The entire US stock market — large, mid, and small cap (~3,800 companies).',
    why: 'The default US equity building block. Extremely low cost, total market coverage.',
    expenseRatio: '0.03%',
    terFootnote: true,
    riskTier: 'medium',
    liquidityHorizon: 't_plus_1',
    tags: ['passive','us-equity','total-market','ultra-low-cost','sec'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  {
    id: 'vxus',
    name: 'VXUS — Vanguard Total International Stock ETF',
    ticker: 'VXUS',
    isin: 'US9220427424',
    type: 'etf',
    bucket: 'GROWTH',
    tier: 1,
    role: 'suggest',
    residenceGeographies: ['US'],
    domicile: 'US',
    regulatoryRegime: 'SEC',
    eligibleWrappers: ['Roth_IRA','Traditional_IRA','401k_traditional','taxable_brokerage_US'],
    currency: 'USD',
    platforms: [
      { name: 'Fidelity', geographies: ['US'] },
      { name: 'Vanguard_US', geographies: ['US'] },
      { name: 'Schwab', geographies: ['US'] },
    ],
    description: 'International stocks excluding the US — developed and emerging markets combined.',
    why: 'Pairs with VTI to build a complete global portfolio with geographic diversification beyond the US.',
    expenseRatio: '0.07%',
    terFootnote: true,
    riskTier: 'medium',
    liquidityHorizon: 't_plus_1',
    tags: ['passive','international','ex-us','low-cost','sec'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  {
    id: 'fzrox',
    name: 'FZROX — Fidelity ZERO Total Market Index Fund',
    type: 'index_fund',
    bucket: 'GROWTH',
    tier: 0,
    role: 'suggest',
    residenceGeographies: ['US'],
    domicile: 'US',
    regulatoryRegime: 'SEC',
    eligibleWrappers: ['Roth_IRA','Traditional_IRA','taxable_brokerage_US'],
    currency: 'USD',
    platforms: [
      { name: 'Fidelity', geographies: ['US'], notes: 'Fidelity accounts only — not transferable' },
    ],
    description: 'Total US market index fund with zero expense ratio. Fidelity account required.',
    why: 'Zero cost means every dollar compounds uninterrupted. Only available within Fidelity.',
    expenseRatio: '0.00%',
    terFootnote: false,
    riskTier: 'medium',
    liquidityHorizon: 't_plus_1',
    tags: ['passive','us-equity','zero-fee','fidelity-only','sec'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  // ── GROWTH — United Kingdom ─────────────────────────────────

  {
    id: 'vwrl-gb',
    name: 'VWRL — Vanguard FTSE All-World (LSE, GBP)',
    ticker: 'VWRL',
    isin: 'IE00B3RBWM25',
    type: 'etf',
    bucket: 'GROWTH',
    tier: 0,
    role: 'suggest',
    residenceGeographies: ['GB'],
    domicile: 'IE',
    regulatoryRegime: 'FCA',
    eligibleWrappers: ['ISA','SIPP','LISA','taxable'],
    currency: 'GBP',
    platforms: [
      { name: 'Vanguard_UK', geographies: ['GB'] },
      { name: 'Hargreaves_Lansdown', geographies: ['GB'] },
      { name: 'AJ_Bell', geographies: ['GB'] },
      { name: 'InvestEngine', geographies: ['GB'], notes: 'Commission-free ISA' },
      { name: 'Freetrade', geographies: ['GB'] },
    ],
    description: 'Global equity — listed on the London Stock Exchange in GBP.',
    why: 'ISA-eligible — growth sheltered from capital gains and dividend tax. The standard UK starting point.',
    expenseRatio: '0.22%',
    terFootnote: true,
    riskTier: 'medium',
    liquidityHorizon: 't_plus_1',
    tags: ['passive','broad-market','isa-eligible','ucits','fca','gbp'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  // ── STABILITY TIER 0 — Emergency Fund ──────────────────────

  {
    id: 'hysa-eu',
    name: 'High-yield savings account (EU)',
    type: 'savings_account',
    bucket: 'STABILITY',
    tier: 0,
    role: 'suggest',
    residenceGeographies: ['NL','BE','DE','LU','GLOBAL_EU'],
    domicile: 'GLOBAL_EU',
    regulatoryRegime: 'AFM',
    eligibleWrappers: ['taxable','box3_NL'],
    currency: 'EUR',
    platforms: [
      { name: 'Trade Republic', geographies: ['DE','NL','BE'], notes: 'Currently ~3.75% variable' },
      { name: 'ING_NL', geographies: ['NL'] },
      { name: 'Rabobank', geographies: ['NL'] },
      { name: 'bank_direct', geographies: ['NL','BE','DE'], notes: 'Compare via raisin.nl' },
    ],
    description: '3–6 months of expenses in an accessible, interest-bearing account.',
    why: 'Before any investment — your emergency buffer prevents you from selling investments at the worst moment.',
    terFootnote: false,
    riskTier: 'very_low',
    liquidityHorizon: 'instant',
    tags: ['emergency-fund','cash','liquid','protection'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  {
    id: 'liquid-fund-in',
    name: 'Liquid Mutual Fund (India)',
    type: 'liquid_fund',
    bucket: 'STABILITY',
    tier: 0,
    role: 'suggest',
    residenceGeographies: ['IN'],
    domicile: 'IN',
    regulatoryRegime: 'SEBI',
    eligibleWrappers: ['NRE','NRO','taxable'],
    currency: 'INR',
    platforms: [
      { name: 'Kuvera', geographies: ['IN'] },
      { name: 'Groww', geographies: ['IN'] },
      { name: 'Zerodha_Coin', geographies: ['IN'] },
    ],
    description: 'Invests in short-term instruments. Near-instant redemption, T+1 credit.',
    why: 'Better yield than savings account, redemption nearly as fast. The Indian emergency fund vehicle of choice.',
    expenseRatio: '~0.15–0.25%',
    terFootnote: true,
    riskTier: 'very_low',
    liquidityHorizon: 't_plus_1',
    tags: ['emergency-fund','liquid','low-risk','india','sebi'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  {
    id: 'hysa-us',
    name: 'High-yield savings account (US)',
    type: 'savings_account',
    bucket: 'STABILITY',
    tier: 0,
    role: 'suggest',
    residenceGeographies: ['US'],
    domicile: 'US',
    regulatoryRegime: 'FINRA',
    eligibleWrappers: ['HSA','taxable_brokerage_US'],
    currency: 'USD',
    platforms: [
      { name: 'Fidelity', geographies: ['US'], notes: 'Cash Management Account' },
      { name: 'Schwab', geographies: ['US'] },
      { name: 'bank_direct', geographies: ['US'], notes: 'Marcus, Ally, Discover Bank' },
    ],
    description: '3–6 months of expenses in an FDIC-insured, accessible account.',
    why: 'Same principle everywhere: liquidity before investment. US HYSA rates currently competitive with short-term bonds.',
    terFootnote: false,
    riskTier: 'very_low',
    liquidityHorizon: 'instant',
    tags: ['emergency-fund','cash','liquid','fdic','us'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  // ── STABILITY TIER 1 — Bond ETFs ────────────────────────────

  {
    id: 'aggh',
    name: 'AGGH — iShares Core Global Aggregate Bond (EUR Hedged)',
    ticker: 'AGGH',
    isin: 'IE00BDBRDM35',
    type: 'bond_etf',
    bucket: 'STABILITY',
    tier: 1,
    role: 'suggest',
    residenceGeographies: ['NL','BE','DE','LU','IE','GB','GLOBAL_EU'],
    domicile: 'IE',
    regulatoryRegime: 'UCITS',
    eligibleWrappers: ['taxable','ISA','SIPP'],
    currency: 'EUR',
    platforms: [
      { name: 'DeGiro', geographies: ['NL','BE','DE'] },
      { name: 'IBKR', geographies: ['NL','BE','DE','LU','GB'] },
    ],
    description: 'Global investment-grade bonds — government and corporate — hedged to EUR.',
    why: 'Standard bond allocation for the Stability bucket. EUR hedge removes currency volatility from a non-EUR bond portfolio.',
    expenseRatio: '0.10%',
    terFootnote: true,
    riskTier: 'low',
    liquidityHorizon: 't_plus_1',
    tags: ['bonds','global','eur-hedged','stability','ucits'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  {
    id: 'bnd',
    name: 'BND — Vanguard Total Bond Market ETF',
    ticker: 'BND',
    isin: 'US9219378356',
    type: 'bond_etf',
    bucket: 'STABILITY',
    tier: 1,
    role: 'suggest',
    residenceGeographies: ['US'],
    domicile: 'US',
    regulatoryRegime: 'SEC',
    eligibleWrappers: ['Roth_IRA','Traditional_IRA','401k_traditional','taxable_brokerage_US'],
    currency: 'USD',
    platforms: [
      { name: 'Vanguard_US', geographies: ['US'] },
      { name: 'Fidelity', geographies: ['US'] },
      { name: 'Schwab', geographies: ['US'] },
    ],
    description: 'The entire US investment-grade bond market — government and corporate.',
    why: 'The standard bond allocation in a US three-fund portfolio. Pairs with VTI + VXUS.',
    expenseRatio: '0.03%',
    terFootnote: true,
    riskTier: 'low',
    liquidityHorizon: 't_plus_1',
    tags: ['bonds','us','total-market','ultra-low-cost','sec'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  {
    id: 'short-duration-debt-in',
    name: 'Short Duration Debt Fund (India, Direct)',
    type: 'debt_fund',
    bucket: 'STABILITY',
    tier: 1,
    role: 'suggest',
    residenceGeographies: ['IN'],
    domicile: 'IN',
    regulatoryRegime: 'SEBI',
    eligibleWrappers: ['NRE','NRO','taxable'],
    currency: 'INR',
    platforms: [
      { name: 'Kuvera', geographies: ['IN'] },
      { name: 'Zerodha_Coin', geographies: ['IN'] },
    ],
    description: 'Bonds with 1–3 year maturity. More stable than equity, better yield than liquid funds.',
    why: 'The Indian Stability bucket equivalent of a bond ETF. Freefincal recommends this category for the non-equity portion.',
    expenseRatio: '~0.25–0.40%',
    terFootnote: true,
    riskTier: 'low',
    liquidityHorizon: 't_plus_1',
    tags: ['bonds','india','short-duration','stability','sebi'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  // ── STABILITY TIER 2 — Money Market / Govt Schemes ─────────

  {
    id: 'xeon',
    name: 'XEON — Xtrackers EUR Overnight Rate Swap ETF',
    ticker: 'XEON',
    isin: 'LU0290358497',
    type: 'money_market_fund',
    bucket: 'STABILITY',
    tier: 2,
    role: 'suggest',
    residenceGeographies: ['NL','BE','DE','LU','IE','GLOBAL_EU'],
    domicile: 'LU',
    regulatoryRegime: 'UCITS',
    eligibleWrappers: ['taxable','box3_NL'],
    currency: 'EUR',
    platforms: [
      { name: 'DeGiro', geographies: ['NL','BE','DE'] },
      { name: 'IBKR', geographies: ['NL','BE','DE','LU'] },
      { name: 'Scalable Capital', geographies: ['DE'] },
    ],
    description: 'Earns the ECB overnight rate. Cash-like with T+1 liquidity.',
    why: 'Parking excess Stability allocation above the emergency fund while maintaining near-instant access.',
    expenseRatio: '0.10%',
    terFootnote: true,
    riskTier: 'very_low',
    liquidityHorizon: 't_plus_1',
    tags: ['money-market','cash-equivalent','ecb-rate','liquid','ucits'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  {
    id: 'uk-premium-bonds',
    name: 'Premium Bonds (UK — NS&I)',
    type: 'govt_savings_scheme',
    bucket: 'STABILITY',
    tier: 2,
    role: 'suggest',
    residenceGeographies: ['GB'],
    domicile: 'GB',
    regulatoryRegime: 'FCA',
    eligibleWrappers: ['taxable'],
    currency: 'GBP',
    platforms: [
      { name: 'NS_and_I', geographies: ['GB'], notes: 'UK residents only — nsandi.com' },
    ],
    description: '100% government-backed savings with monthly prize draws. Up to £50,000. Instant access.',
    why: 'Prize rate equivalent to ~4.4% average. Fully government-backed, all prizes tax-free, fully liquid.',
    terFootnote: false,
    riskTier: 'capital_guaranteed',
    liquidityHorizon: 'instant',
    tags: ['govt-backed','uk','tax-free','liquid','no-market-risk'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  {
    id: 'us-ibonds',
    name: 'Series I Savings Bonds (US Treasury)',
    type: 'govt_savings_scheme',
    bucket: 'STABILITY',
    tier: 2,
    role: 'suggest',
    residenceGeographies: ['US'],
    domicile: 'US',
    regulatoryRegime: 'SEC',
    eligibleWrappers: ['taxable_brokerage_US'],
    currency: 'USD',
    platforms: [
      { name: 'TreasuryDirect', geographies: ['US'], notes: 'Only at TreasuryDirect.gov — $10,000/yr limit' },
    ],
    description: 'US government bond with inflation-adjusted interest. $10,000/year per person.',
    why: 'Inflation protection with zero credit risk. No market risk. Strong Stability holding for US residents.',
    terFootnote: false,
    riskTier: 'capital_guaranteed',
    liquidityHorizon: 'months_12',
    riskWarning: '1-year minimum hold. 3-month interest penalty if redeemed before 5 years.',
    tags: ['govt-backed','inflation-protected','us','annual-limit'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  // ── LOCKED TIER 0 — Employer pensions + wrappers ───────────

  {
    id: 'nl-pensioenfonds',
    name: 'Dutch employer pension (Pensioenfonds)',
    type: 'pension_scheme',
    bucket: 'LOCKED',
    tier: 0,
    role: 'suggest',
    residenceGeographies: ['NL'],
    domicile: 'NL',
    regulatoryRegime: 'AFM',
    eligibleWrappers: ['Pension_NL'],
    currency: 'EUR',
    platforms: [
      { name: 'employer', geographies: ['NL'], notes: 'ABP, PFZW, PMT, PME by sector' },
    ],
    description: 'Netherlands mandatory occupational pension — employee and employer contribute monthly.',
    why: 'Employer match is free money. Always the highest-priority LOCKED holding. Check your pension fund portal.',
    terFootnote: false,
    riskTier: 'medium',
    liquidityHorizon: 'until_retirement',
    tags: ['pension','netherlands','employer-match','mandatory','locked'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  {
    id: 'de-bav',
    name: 'bAV — Betriebliche Altersvorsorge (Germany)',
    type: 'pension_scheme',
    bucket: 'LOCKED',
    tier: 0,
    role: 'suggest',
    residenceGeographies: ['DE'],
    domicile: 'DE',
    regulatoryRegime: 'BaFin',
    eligibleWrappers: ['bAV_DE'],
    currency: 'EUR',
    platforms: [
      { name: 'employer', geographies: ['DE'], notes: 'Ask HR — employer-specific provider' },
    ],
    description: 'German occupational pension. Pre-tax contributions. Employer required to add 15% on top.',
    why: 'Pre-tax contributions reduce taxable income immediately. Mandatory employer 15% makes this worth maximising first.',
    terFootnote: false,
    riskTier: 'medium',
    liquidityHorizon: 'until_retirement',
    tags: ['pension','germany','pre-tax','employer-match','locked'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  {
    id: 'roth-ira',
    name: 'Roth IRA (United States)',
    type: 'retirement_account',
    bucket: 'LOCKED',
    tier: 0,
    role: 'suggest',
    residenceGeographies: ['US'],
    domicile: 'US',
    regulatoryRegime: 'SEC',
    eligibleWrappers: ['Roth_IRA'],
    currency: 'USD',
    platforms: [
      { name: 'Fidelity', geographies: ['US'] },
      { name: 'Vanguard_US', geographies: ['US'] },
      { name: 'Schwab', geographies: ['US'] },
    ],
    description: 'Tax-free growth and withdrawals. $7,000/year limit (2024). Income limits apply.',
    why: 'One of the most tax-efficient wrappers available. Contributions (not earnings) can be withdrawn anytime.',
    terFootnote: false,
    riskTier: 'medium',
    liquidityHorizon: 'until_retirement',
    tags: ['retirement','tax-free','us','locked','high-priority'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  {
    id: 'uk-isa',
    name: 'Stocks & Shares ISA (United Kingdom)',
    type: 'retirement_account',
    bucket: 'LOCKED',
    tier: 0,
    role: 'suggest',
    residenceGeographies: ['GB'],
    domicile: 'GB',
    regulatoryRegime: 'FCA',
    eligibleWrappers: ['ISA'],
    currency: 'GBP',
    platforms: [
      { name: 'Vanguard_UK', geographies: ['GB'] },
      { name: 'Hargreaves_Lansdown', geographies: ['GB'] },
      { name: 'AJ_Bell', geographies: ['GB'] },
      { name: 'InvestEngine', geographies: ['GB'] },
      { name: 'Freetrade', geographies: ['GB'] },
    ],
    description: '£20,000/year tax-free. No capital gains tax, no dividend tax on anything inside.',
    why: 'UK\'s most powerful investment wrapper. Fill this before investing in taxable accounts.',
    terFootnote: false,
    riskTier: 'medium',
    liquidityHorizon: 'instant',
    tags: ['isa','uk','tax-free','locked','high-priority'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  {
    id: 'uk-lisa',
    name: 'Lifetime ISA (United Kingdom)',
    type: 'retirement_account',
    bucket: 'LOCKED',
    tier: 0,
    role: 'suggest',
    residenceGeographies: ['GB'],
    domicile: 'GB',
    regulatoryRegime: 'FCA',
    eligibleWrappers: ['LISA'],
    currency: 'GBP',
    platforms: [
      { name: 'AJ_Bell', geographies: ['GB'] },
      { name: 'Hargreaves_Lansdown', geographies: ['GB'] },
      { name: 'Moneybox', geographies: ['GB'] },
    ],
    description: '£4,000/year with 25% government bonus — up to £1,000 free per year.',
    why: '25% bonus is an immediate guaranteed return. Under-used by globally mobile professionals with UK ties.',
    terFootnote: false,
    riskTier: 'medium',
    liquidityHorizon: 'years_5',
    riskWarning: '25% withdrawal penalty applies if used for anything other than first home or retirement at 60+.',
    tags: ['lisa','uk','government-bonus','locked','first-home'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  // ── LOCKED — India ──────────────────────────────────────────

  {
    id: 'in-ppf',
    name: 'PPF — Public Provident Fund (India)',
    type: 'govt_savings_scheme',
    bucket: 'LOCKED',
    tier: 0,
    role: 'suggest',
    residenceGeographies: ['IN'],
    domicile: 'IN',
    regulatoryRegime: 'MoF_IN',
    eligibleWrappers: ['PPF'],
    currency: 'INR',
    platforms: [
      { name: 'Post_Office_IN', geographies: ['IN'] },
      { name: 'bank_direct', geographies: ['IN'], notes: 'SBI, PNB, any nationalised bank' },
    ],
    description: 'Government-backed 15-year scheme. 7.1% p.a. EEE status — fully exempt.',
    why: 'EEE: contribution deductible, returns tax-free, maturity tax-free. Highest risk-free return in India.',
    terFootnote: false,
    riskTier: 'capital_guaranteed',
    liquidityHorizon: 'years_15',
    tags: ['govt-backed','india','eee','tax-free','locked','15-year'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  {
    id: 'in-epf',
    name: 'EPF — Employees Provident Fund (India)',
    type: 'pension_scheme',
    bucket: 'LOCKED',
    tier: 0,
    role: 'suggest',
    residenceGeographies: ['IN'],
    domicile: 'IN',
    regulatoryRegime: 'EPFO',
    eligibleWrappers: ['EPF'],
    currency: 'INR',
    platforms: [
      { name: 'EPFO_portal', geographies: ['IN'], notes: 'Employer-routed — check UAN portal' },
    ],
    description: 'Mandatory retirement savings for salaried employees. 8.25% p.a. Employee + employer both contribute 12% of basic.',
    why: 'Employer contribution is free money — always the highest priority. Check your UAN to confirm correct crediting.',
    terFootnote: false,
    riskTier: 'capital_guaranteed',
    liquidityHorizon: 'until_retirement',
    tags: ['govt-backed','india','mandatory','employer-match','locked'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  {
    id: 'in-elss',
    name: 'ELSS — Equity Linked Savings Scheme (India)',
    type: 'active_mutual_fund',
    bucket: 'LOCKED',
    tier: 1,
    role: 'suggest',
    residenceGeographies: ['IN'],
    domicile: 'IN',
    regulatoryRegime: 'SEBI',
    eligibleWrappers: ['ELSS','NRE','NRO'],
    currency: 'INR',
    platforms: [
      { name: 'Zerodha_Coin', geographies: ['IN'] },
      { name: 'Groww', geographies: ['IN'] },
      { name: 'Kuvera', geographies: ['IN'] },
    ],
    description: 'Equity mutual fund with 3-year lock-in and 80C deduction up to ₹1.5L/year.',
    why: 'Shortest lock-in of all 80C instruments. Equity returns historically exceed PPF over long periods.',
    expenseRatio: '~0.60–1.00%',
    terFootnote: true,
    riskTier: 'medium_high',
    liquidityHorizon: 'years_3',
    tags: ['india','80c','tax-saving','equity','locked','3-year-lock-in'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  {
    id: 'in-nps',
    name: 'NPS — National Pension System (India)',
    type: 'pension_scheme',
    bucket: 'LOCKED',
    tier: 1,
    role: 'suggest',
    residenceGeographies: ['IN'],
    domicile: 'IN',
    regulatoryRegime: 'PFRDA',
    eligibleWrappers: ['NPS_tier1','NPS_tier2'],
    currency: 'INR',
    platforms: [
      { name: 'NSDL_CRA', geographies: ['IN'] },
      { name: 'Zerodha', geographies: ['IN'] },
      { name: 'HDFC_Securities', geographies: ['IN'] },
    ],
    description: 'Government pension scheme. Additional ₹50,000 deduction under 80CCD(1B) beyond 80C.',
    why: 'Extra ₹50,000 deduction above 80C limit. Useful once PPF and ELSS are maxed. NRIs cannot open new accounts.',
    terFootnote: false,
    riskTier: 'medium',
    liquidityHorizon: 'until_retirement',
    riskWarning: 'NRIs cannot open new NPS accounts. Existing accounts can be maintained.',
    tags: ['india','pension','80ccd','tax-saving','locked','nri-restriction'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  // ── TRACK ONLY — Crowdfunding & Alternatives ───────────────

  {
    id: 'crowdcube',
    name: 'Crowdcube — equity crowdfunding',
    type: 'equity_crowdfunding',
    bucket: 'GROWTH',
    tier: 3,
    role: 'track_only',
    residenceGeographies: ['GB','NL','BE','DE','GLOBAL_EU'],
    domicile: 'GB',
    regulatoryRegime: 'FCA',
    eligibleWrappers: ['taxable'],
    currency: 'GBP',
    platforms: [
      { name: 'Crowdcube', geographies: ['GB','NL','BE','DE'] },
    ],
    description: 'Equity stakes in early-stage UK and European companies via Crowdcube platform.',
    why: '',
    terFootnote: false,
    riskTier: 'illiquid',
    liquidityHorizon: 'unknown',
    riskWarning: 'Equity crowdfunding is high risk and illiquid. Most startups fail. Capital is at risk. No guaranteed exit.',
    tags: ['crowdfunding','illiquid','track-only','unregulated','high-risk'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  {
    id: 'seedrs',
    name: 'Seedrs — equity crowdfunding',
    type: 'equity_crowdfunding',
    bucket: 'GROWTH',
    tier: 3,
    role: 'track_only',
    residenceGeographies: ['GB','NL','BE','DE','GLOBAL_EU'],
    domicile: 'GB',
    regulatoryRegime: 'FCA',
    eligibleWrappers: ['taxable'],
    currency: 'GBP',
    platforms: [
      { name: 'Seedrs', geographies: ['GB','NL','BE','DE'] },
    ],
    description: 'Equity stakes in early-stage companies via Seedrs (now Republic Europe).',
    why: '',
    terFootnote: false,
    riskTier: 'illiquid',
    liquidityHorizon: 'unknown',
    riskWarning: 'Equity crowdfunding is high risk and illiquid. Most startups fail. Capital is at risk. No guaranteed exit.',
    tags: ['crowdfunding','illiquid','track-only','high-risk'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  {
    id: 'crypto-btc',
    name: 'Bitcoin (BTC)',
    type: 'crypto_spot',
    bucket: 'GROWTH',
    tier: 3,
    role: 'track_only',
    residenceGeographies: ['GLOBAL'],
    domicile: 'GLOBAL',
    regulatoryRegime: 'unregulated',
    eligibleWrappers: ['taxable'],
    currency: 'USD',
    platforms: [
      { name: 'other', geographies: ['GLOBAL'], notes: 'Coinbase, Binance, Kraken, Bitvavo (NL)' },
    ],
    description: 'Bitcoin — the largest cryptocurrency by market cap.',
    why: '',
    terFootnote: false,
    riskTier: 'very_high',
    liquidityHorizon: 'instant',
    riskWarning: 'Crypto assets are highly volatile and unregulated in most jurisdictions. Value can drop to zero.',
    tags: ['crypto','track-only','unregulated','very-high-risk'],
    addedAt: '2026-03-17',
    isActive: true,
  },

  // ── GLOBAL FALLBACK ─────────────────────────────────────────

  {
    id: 'global-vwce-fallback',
    name: 'VWCE — Vanguard FTSE All-World (Global access)',
    ticker: 'VWCE',
    isin: 'IE00BK5BQT80',
    type: 'etf',
    bucket: 'GROWTH',
    tier: 0,
    role: 'suggest',
    residenceGeographies: ['GLOBAL'],
    domicile: 'IE',
    regulatoryRegime: 'UCITS',
    eligibleWrappers: ['taxable'],
    currency: 'EUR',
    platforms: [
      { name: 'IBKR', geographies: ['GLOBAL'], notes: 'IBKR International — available in most countries' },
    ],
    description: 'Globally accessible world equity ETF via IBKR International.',
    why: 'The most accessible global equity instrument while we build out your specific region\'s catalogue.',
    expenseRatio: '0.22%',
    terFootnote: true,
    riskTier: 'medium',
    liquidityHorizon: 't_plus_1',
    tags: ['passive','broad-market','global','ucits','ibkr-accessible','fallback'],
    addedAt: '2026-03-17',
    isActive: true,
  },

]

// ─── Helpers ─────────────────────────────────────────────────

export function getInstrumentsForGeography(
  geographyCode: string
): InstrumentCatalogueEntry[] {
  const code = geographyCode as GeographyCode
  return INSTRUMENT_CATALOGUE.filter(
    (i) =>
      i.isActive &&
      (i.residenceGeographies.includes(code) ||
        i.residenceGeographies.includes('GLOBAL_EU' as GeographyCode) ||
        i.residenceGeographies.includes('GLOBAL' as GeographyCode))
  )
}

export function getSuggestableInstruments(
  geographyCode: string
): InstrumentCatalogueEntry[] {
  return getInstrumentsForGeography(geographyCode).filter(
    (i) => i.role === 'suggest'
  )
}

export function getInstrumentsByTierAndBucket(
  bucket: InstrumentCatalogueEntry['bucket'],
  tier: number,
  geographyCode: string
): InstrumentCatalogueEntry[] {
  return getSuggestableInstruments(geographyCode).filter(
    (i) => i.bucket === bucket && i.tier === tier
  )
}

export function isKnownGeography(geographyCode: string): boolean {
  const knownCodes = ['NL','BE','DE','LU','IN','US','GB','IE','FR','AT','CH','SE','SG','AE']
  return knownCodes.includes(geographyCode)
}

export const TER_FOOTNOTE =
  'TER shown is indicative. Verify current expense ratio before investing.'

export const UNKNOWN_GEOGRAPHY_MESSAGE =
  "We're building your region's instrument list. Here's what works globally while we do."

// Suppress unused import warning — TRACK_ONLY_TYPES is exported for
// consumers who need to filter suggestions at the call site.
void TRACK_ONLY_TYPES
