import type { SpendCategory } from '../types/spend'

export type GeographyKeywordsMap = Partial<Record<SpendCategory, string[]>>

export type MerchantKeywordsType = Record<'NL' | 'IN' | 'EU' | 'GLOBAL', GeographyKeywordsMap>

export const MERCHANT_KEYWORDS: MerchantKeywordsType = {
  NL: {
    groceries: [
      'albert heijn',
      'jumbo',
      'lidl',
      'aldi',
      'plus supermarkt',
      'dirk',
      'coop supermarkt',
      'picnic',
      'dekamarkt',
      'spar',
    ],
    eating_out: [
      'thuisbezorgd',
      'uber eats',
      'deliveroo',
      'mcdonalds',
      'burger king',
      'kfc',
      'dominos',
      'new york pizza',
      'starbucks',
      'cafe',
    ],
    transport: [
      'ns reizigers',
      'connexxion',
      'arriva',
      'gvb',
      'ret',
      'htm',
      'ov chipkaart',
      'bolt',
      'swapfiets',
      'anwb',
    ],
    utilities: [
      'vattenfall',
      'eneco',
      'nuon',
      'essent',
      'greenchoice',
      'ziggo',
      'kpn',
      't-mobile',
      'vodafone',
      'xs4all',
    ],
    housing: [
      'hypotheek',
      'abn amro hypotheek',
      'woningborg',
      'ing hypotheek',
      'rabobank hypotheek',
    ],
    insurance: [
      'zorgverzekering',
      'centraal beheer',
      'nationale nederlanden',
      'aegon',
      'achmea',
      'ditzo',
      'anderzorg',
      'cz groep',
      'menzis',
      'vgz',
    ],
    health: [
      'apotheek',
      'huisarts',
      'tandarts',
      'etos',
      'kruidvat',
      'da drogist',
    ],
    shopping: [
      'bol.com',
      'coolblue',
      'mediamarkt',
      'hema',
      'action',
      'primark',
      'h&m',
      'zara',
      'ikea',
      'blokker',
    ],
    subscriptions: [
      'netflix',
      'spotify',
      'npo plus',
      'videoland',
      'blendle',
      'adobe',
      'microsoft 365',
      'apple',
      'google',
      'amazon prime',
    ],
  },

  IN: {
    groceries: [
      'bigbasket',
      'grofers',
      'blinkit',
      'zepto',
      'swiggy instamart',
      'dmart',
      'reliance fresh',
      'more supermarket',
      'nature basket',
      'jiomart',
    ],
    eating_out: [
      'swiggy',
      'zomato',
      'mcdonald',
      'dominos',
      'pizza hut',
      'kfc',
      'burger king',
      'cafe coffee day',
      'barista',
      'starbucks',
    ],
    transport: [
      'ola',
      'uber',
      'rapido',
      'namma yatri',
      'blumart',
      'metro rail',
      'irctc',
      'redbus',
      'makemytrip transport',
      'fasttag',
    ],
    utilities: [
      'bescom',
      'msedcl',
      'tata power',
      'adani electricity',
      'airtel',
      'jio',
      'vi vodafone',
      'bsnl',
      'mahanagar gas',
      'indraprastha gas',
    ],
    health: [
      'apollo pharmacy',
      'medplus',
      'netmeds',
      '1mg',
      'pharmeasy',
      'practo',
      'lenskart',
    ],
    subscriptions: [
      'hotstar',
      'netflix',
      'amazon prime',
      'sony liv',
      'zee5',
      'spotify',
      'youtube premium',
      'apple',
      'google',
      'adobe',
    ],
    shopping: [
      'flipkart',
      'amazon',
      'myntra',
      'nykaa',
      'ajio',
      'meesho',
      'snapdeal',
      'tata cliq',
      'reliance digital',
      'croma',
    ],
    investment_transfer: [
      'zerodha',
      'groww',
      'upstox',
      'angelone',
      'hdfc securities',
      'icicidirect',
      'sbicard mutual',
      'paytm money',
    ],
  },

  EU: {
    groceries: [
      'carrefour',
      'lidl',
      'aldi',
      'rewe',
      'edeka',
      'kaufland',
      'mercadona',
      'leclerc',
      'tesco',
      'sainsburys',
      'waitrose',
      'migros',
    ],
    transport: [
      'deutsche bahn',
      'db bahn',
      'sncf',
      'renfe',
      'eurostar',
      'flixbus',
      'blablacar',
      'uber',
      'bolt',
      'free now',
    ],
    eating_out: [
      'mcdonalds',
      'burger king',
      'kfc',
      'subway',
      'starbucks',
      'costa coffee',
      'pret a manger',
      'deliveroo',
      'wolt',
      'lieferando',
    ],
    utilities: [
      'edf',
      'vattenfall',
      'e.on',
      'rwe',
      'engie',
      'enel',
      'vodafone',
      'orange',
      'o2',
      'telekom',
    ],
    shopping: [
      'amazon',
      'zalando',
      'about you',
      'h&m',
      'zara',
      'primark',
      'fnac',
      'saturn',
      'mediamarkt',
      'ikea',
    ],
    subscriptions: [
      'netflix',
      'spotify',
      'amazon prime',
      'apple',
      'google',
      'adobe',
      'microsoft',
      'disney',
      'sky',
      'canal plus',
    ],
  },

  GLOBAL: {
    groceries: [
      'whole foods',
      'trader joes',
      'costco',
      'walmart',
      'lidl',
      'aldi',
    ],
    eating_out: [
      'mcdonalds',
      'burger king',
      'kfc',
      'subway',
      'starbucks',
      'dominos pizza',
      'pizza hut',
      'uber eats',
      'deliveroo',
    ],
    transport: [
      'uber',
      'lyft',
      'grab',
      'bolt',
      'gojek',
      'free now',
      'cabify',
    ],
    subscriptions: [
      'netflix',
      'spotify',
      'apple',
      'google play',
      'amazon prime',
      'disney plus',
      'adobe',
      'microsoft',
      'dropbox',
      'youtube',
    ],
    shopping: [
      'amazon',
      'ebay',
      'aliexpress',
      'shein',
      'h&m',
      'zara',
      'ikea',
      'apple store',
    ],
    travel: [
      'booking.com',
      'airbnb',
      'expedia',
      'hotels.com',
      'skyscanner',
      'kayak',
      'klm',
      'ryanair',
      'easyjet',
      'british airways',
    ],
    income: [
      'salary',
      'payroll',
      'salaris',
    ],
    investment_transfer: [
      'degiro',
      'interactive brokers',
      'trading 212',
      'etoro',
      'vanguard',
      'blackrock',
    ],
    transfer: [
      'wise',
      'revolut',
      'paypal',
      'tikkie',
      'monzo',
      'venmo',
    ],
    health: [
      'pharmacy',
      'apotheek',
      'boots',
      'superdrug',
    ],
    insurance: [
      'insurance',
      'assurance',
      'verzekering',
      'allianz',
      'axa',
      'zurich',
      'generali',
    ],
  },
}
